name: Dynapgen-app CD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Installing Packages
        run: npm install
      - name: "Running Linter"
        run: npm run lint
      - name: Setting up env file
        env:
          VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}
        run: |
          echo "VITE_BASE_URL=${VITE_BASE_URL}" > .env.production

      - name: Deploying
        run: |
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git config --global user.name "${{ secrets.USER_NAME }}"
          git remote set-url origin https://${{ secrets.API_KEY }}@github.com/${{ secrets.USER_NAME }}/dynapgen-app.git
          npm run deploy